### ISSUE TITLE
Add social media cards for Linkedin and Facebook

### ISSUE THREAD

**Issue by dcalvin** [pingcap/website#126]
Currently, we only have Twitter cards implemented; However, we sometimes also post on LinkedIn and Facebook, which currently does not preview well. 

Preferably we can add them quickly.

**Comment by std4453** [comment]
LinkedIn seems to work alright, from `zh-preview`.

Facebook uses `og:url` meta as canonical URL, which is currently `https://pingcap.com` for every page, letting them use the very same share images, which is the favicon.

I'm removing `og:url` here, however I don't know whether it has other impacts.

**Comment by dcalvin** [comment]
By working all right, do you mean it can preview with the big image and title description as we have for Twitter? I just tried - seems still not working fine @std4453 
![image](https://user-images.githubusercontent.com/2503903/89150999-78644480-d592-11ea-85e9-2ab5b6b99562.png)

**Comment by std4453** [comment]
@dcalvin 
You're sharing from `en.pingcap.com`, which is a very old version, I'm talking about https://pingcap-zh-preview.netlify.app/ where LinkedIn shares should be working.

My pull request about should fix facebook, which can be previewed [here](https://deploy-preview-157--pingcap-zh-preview.netlify.app/).

**Comment by dcalvin** [comment]
Rt! Thanks for clarifying. It works great! So when will they get merged?
