### ISSUE TITLE
Add the copy feature for code blocks in case studies and blog posts

### ISSUE THREAD

**Issue by CaitinChen** [pingcap/website#147]
For example, in the post: https://pingcap.com/blog/get-tidb-cluster-up-in-only-one-minute

Code blocks do not support the copy feature.

(But in the old website, we have code block copy feature.)

@YiniXu9506 PTAL

**Comment by YiniXu9506** [comment]
@CaitinChen Did you remove the `{{ copyable }}` snippet code on blog markdown?

**Comment by YiniXu9506** [comment]
The feature copy code has been supported online. You can add `{{ copyable }}` snippet code now.
