### ISSUE TITLE
Fix download and subscription buttons in the middle of blog posts and case studies

### ISSUE THREAD

**Issue by CaitinChen** [pingcap/website#149]
The download and subscription buttons in the middle of blog posts are not normally displayed, so they have been hidden. 
For example, https://pingcap.com/blog/how_to_spin_up_an_htap_database_in_5_minutes_with_tidb_tispark

Please remember to fix this issue. Thanks.

@YiniXu9506

**Comment by YiniXu9506** [comment]
The buttons on middle of blog posts have tracking code, which will send events to old-website project, so we cannot display the buttons now. We need to talk later about the tracking code update.
