### ISSUE TITLE
Allow users to see the full article via clicking the case study's summary on the customer logo wall

### ISSUE THREAD

**Issue by CaitinChen** [pingcap/website#169]
In this [page](https://pingcap.com/case-studies), we can't directly click a case study's summary to visit the full article. 
When we mouse over a case study's summary, to see the full case study, we have to scroll down to click "Read more >". If users don't know they can scroll down, they won't see the post.

We hope: when users mouse over a case study's summary, the summary text will turn blue and become clickable. Users can click the summary to see the full article. 

If you have any question, you can contact me. Thanks.

**Comment by YiniXu9506** [comment]
@dcalvin Would you PTAL at this issue. If you agree to change this, let @sykp241095 and UI team know about this and update the prototype.

**Comment by dcalvin** [comment]
> @dcalvin Would you PTAL at this issue. If you agree to change this, let @sykp241095 and UI team know about this and update the prototype.

Yes. Thanks for the update. I will proceed with next steps.

**Comment by dcalvin** [comment]
Please make the UI similar to our Success Stories in the old website. 
 
![image](https://user-images.githubusercontent.com/2503903/90362650-b03fb180-e093-11ea-9aa3-b8d3c3502414.png)

**Comment by CaitinChen** [comment]
We hope there is a scrollbar on the right for the summary.

![image](https://user-images.githubusercontent.com/34535727/91788915-04c06080-ec40-11ea-84fc-1d68e9562242.png)

**Comment by YiniXu9506** [comment]
Has been updated online. Related [PR](https://github.com/pingcap/website/pull/231)
