### ISSUE TITLE
Let the information on the right of case studies and blog posts hover over the page

### ISSUE THREAD

**Issue by CaitinChen** [pingcap/website#188]
Currently, the information (for example,**What's on this page**, **Related posts**, **Welcome to share this post!**, **Categories**, **Tags**) on the right side of the blog and case study pages doesn't move as users scroll down the page. When users scroll down to the middle or the end of the post, they can't see the information on the right side.

We hope in the following pages, the right-side information can always hover over the page so that users won't miss this information:

- Every case study post, like [this one](https://pingcap.com/case-studies/horizontally-scaling-hive-metastore-database-by-migrating-from-mysql-to-tidb)
- The [blog overview page](https://pingcap.com/blog)
- Every blog post, like [this one](https://pingcap.com/blog/tidb-4.0-elastic-real-time-htap-database-ready-for-cloud)

**Comment by YiniXu9506** [comment]
@dcalvin PTAL

**Comment by dcalvin** [comment]
> @dcalvin PTAL. From my opinion, I would not suggest to fix the information position, you can refer to other site about this section.

Let me take a look around and get back to this.

**Comment by dcalvin** [comment]
As discussed with @YiniXu9506, we clarified the requirement is just to make the right-side navigation fixed (not scrolling with the blog text).  Please proceed and assign the task. Thanks.
