### ISSUE TITLE
Open all links on the website in new tabs

### ISSUE THREAD

**Issue by CaitinChen** [pingcap/website#201]
Currently, when we click a link on the PingCAP website, the current page is replaced with a new page, sometimes a page of a non-PingCAP website. This reduces readers' dwell time and affects our SEO ranking.

We hope: when we click a link on the PingCAP website, we will open a page in a new tab.

**Comment by YiniXu9506** [comment]
@CaitinChen Normally, the internal links will open in the current Tab and the external links open in a new Tab on browser. It's unreasonable to open all links in a Tab. The behavior mentioned above does not have good effect on SEO, see [google support ](https://support.google.com/analytics/answer/1009409?hl=en). 

So we are not going to proceed this issue.
