### ISSUE TITLE
Support display all blog posts via tag and category icons

### ISSUE THREAD

**Issue by CaitinChen** [pingcap/website#211]
Currently, in the [blog page](https://pingcap.com/blog), when we click a category icon, we will see posts of this category. In this case, when we want to see all posts, we have to click "Blog" in the horizontal navigation bar at the top of the page or the Back button in the browser.

We hope:
When we've chosen a tag or category icon, if we click this icon again, the choosing effect is canceled. (Then, we will see all posts.) 

@dcalvin FYI.

**Comment by YiniXu9506** [comment]
@CaitinChen All the tags and categories button on the right side of blog page are links, not check buttons. This is not a strong requirement to change this. Please refer the logic on other sites.

**Comment by CaitinChen** [comment]
@YiniXu9506 OK.
After investigation and discussion with @dcalvin, we hope you can add a new category named "All". When we click "All", we can see all blog posts. Thanks.
