### ISSUE TITLE
Enlarge the video interface

### ISSUE THREAD

**Issue by CaitinChen** [pingcap/website#217]
In our new website, the video in [this post](https://pingcap.com/blog/observe-distributed-databases-to-discover-unknowns) is too small. In the old website, it is displayed properly.

Please enlarge the video interface on the new website. Thanks.

**Comment by YiniXu9506** [comment]
The video size has been updated, PTAL @CaitinChen

**Comment by CaitinChen** [comment]
@YiniXu9506 Thanks a lot.
