### ISSUE TITLE
Community edition download page is shaking when click SelectBox

### ISSUE THREAD

**Issue by cw1997** [pingcap/website#274]
https://github.com/pingcap/website/blob/3d50973ad6c2a64d48c5930663a126886b09456c/src/pages/download/community.js#L123

Community edition download page is shaking when click SelectBox, because the right scroll is hidden when SelectBox is opened, and the page width will be smaller without right scroll.

**Comment by YiniXu9506** [comment]
This page does not exist now, add aliases to this page, and redirect to page `/download`. Use gatsby API [`createRedirect`](https://www.gatsbyjs.com/docs/actions/#createRedirect) to redirect page.
