### ISSUE TITLE
Adjust headings and font in English blog posts, case studies, and docs

### ISSUE THREAD

**Issue by CaitinChen** [pingcap/website#352]
@YiniXu9506 After our team discussed with Alex Chen, we want to change headings and the font in English blog posts, case studies, and docs. Alex Chen will tell you her detailed design. Thanks.

Via https://github.com/pingcap/pingcap.github.io/issues/544

**Comment by YiniXu9506** [comment]
@CaitinChen I haven't received the change guide from Alex. Did you confirm this with her?

**Comment by CaitinChen** [comment]
@YiniXu9506 I'll ask her again.
