### ISSUE TITLE
Remove "Customer Reference" clause from "TiDB Cloud Services Agreement" online document (https://en.pingcap.com/legal/tidb-cloud-services-agreement/)

### ISSUE THREAD

**Issue by dingyiyu04** [pingcap/website#385]
Please help remove the clause 15.6 "Customer Reference" from "TiDB Cloud Services Agreement" online document (https://en.pingcap.com/legal/tidb-cloud-services-agreement/).
![image](https://user-images.githubusercontent.com/87468777/125750768-ecd72364-f03e-476a-97ee-4e278f8f8588.png)

**Comment by YiniXu9506** [comment]
There is a reference to 15.6 in the clause 5.6, please check if you also want to update that.

**Comment by dingyiyu04** [comment]
Yes, the clause 5.6 should be updated to the follows:
"The following Sections will survive the termination or expiration of this CSA: Sections 4.1 to 4.4, Sections 6.4 to 6.6, Sections 8 to 11, and Section 14."
