### ISSUE TITLE
Add TiDB Monthly page

### ISSUE THREAD

**Issue by dcalvin** [pingcap/website#71]
No design is needed. Simply inherit the original design, as in  https://pingcap.com/weekly/

**Comment by TomShawn** [comment]
Reference: [TiDB Monthly 迁移至新官网需求汇总](https://docs.google.com/document/d/1zVzq4sYaGzTKSDsdH6UgPN-yIG76oHKM8Dta9LoQgcQ/edit?ts=5f23b275#heading=h.hqoc76tfasvm)

**Comment by YiniXu9506** [comment]
We need prototype to process this issue.

**Comment by dcalvin** [comment]
Hold this request for now.

**Comment by YiniXu9506** [comment]
Sync up with Calvin, Weekly series pages are not going to maintain in the future. https://pingcap.com/weekly/* will be redirected to an announcement page.

![image](https://user-images.githubusercontent.com/34967660/118228537-f1e37880-b4bc-11eb-8c0a-79e04756eb36.png)
