### ISSUE TITLE
Add bookmark navigation for success stories  

### ISSUE THREAD

**Issue by dcalvin** [pingcap/website#74]
Currently, Success Stories are in the same style as blog articles. It would be better to provide a bookmark navigation where all the user cases are listed and categorized. Similar to https://pingcap.com/cases-cn/user-case-meituandianping/

**Comment by dcalvin** [comment]
Raising priority for this one, as we have some adapters with multiple case studies, so a nav bar is required to easily locate all related case studies @sykp241095

**Comment by YiniXu9506** [comment]
We need prototype to process this issue.

**Comment by dcalvin** [comment]
This requirement is superseded by https://github.com/pingcap/website/issues/76
