### ISSUE TITLE
Add tags for Success Stories 

### ISSUE THREAD

**Issue by dcalvin** [pingcap/website#76]
Currently all articles under Success Stories don't have tags.

**Comment by YiniXu9506** [comment]
@dcalvin The description of this feature is not very clear, you can talk to UI designer and provide the design draft.

**Comment by dcalvin** [comment]
The design is similar to the blog, except Case Studies page hasz a different set of tag filters, as described below:

- All  - shows all case studies in chronological order (latest to oldest)
- Industry - filter by industries 
- Company - filter by specific company 
@YiniXu9506 @CaitinChen FYI
