### ISSUE TITLE
Change image left-justified to center-justified in blog posts and case studies

### ISSUE THREAD

**Issue by CaitinChen** [pingcap/website#80]
For example: 

- https://pingcap.com/blog/how-we-reduced-multi-region-read-latency-and-network-traffic-by-50 
- https://pingcap.com/case-studies/tidb-in-xiaomi

@YiniXu9506 PTAL

**Comment by YiniXu9506** [comment]
@wanyoulc PTAL

**Comment by CaitinChen** [comment]
Thanks.
